### PR TITLE
Add names to review comments

### PR DESCRIPTION
**Pull request by chrismytton**
Fixes https://github.com/everypolitician/review_changes/issues/3

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Looks good :+1: — is this ready to put live? Keen to see it in action…

**Comment by chrismytton** [comment]
@tmtmtmtm Oops, yes I totally meant to put this live yesterday! Will do that now…

**Comment by chrismytton** [comment]
This is now live

**Comment by chrismytton** [comment]
Example of this working - https://github.com/everypolitician/everypolitician-data/pull/4072#issuecomment-182318473

**Comment by tmtmtmtm** [comment]
Yay. Though https://github.com/everypolitician/everypolitician-data/pull/4072/files looks a _lot_ more complex than that suggests, and is probably a really good test case for working out what features to add to the Reviewer next!

**Pull request merged**
